"use client";

import { useState } from "react";
import { BookOpen, Calendar, ArrowLeft, Clock, Tag } from "lucide-react";
import { sounds } from "@/lib/sound";

type Article = {
  id: string;
  title: string;
  date: string;
  readTime: string;
  tag: string;
  summary: string;
  content: React.ReactNode;
};

const ARTICLES: Article[] = [
  {
    id: "graph-rag",
    title: "Architecting a 10K+ Node Enterprise Graph RAG System with Neo4j & Azure OpenAI",
    date: "July 2026",
    readTime: "5 min read",
    tag: "Graph AI & Systems",
    summary:
      "How we built a domain-aware Cypher query generation pipeline over 10K+ nodes and 25K+ relationships at NCR Atleos, reducing Power BI scaffolding time by ~60%.",
    content: (
      <div className="space-y-4 text-xs leading-relaxed text-black/80">
        <p>
          At <strong>NCR Atleos</strong>, enterprise knowledge was heavily fragmented across relational databases, internal document stores, and microservice APIs. Standard vector-search RAG (Retrieval-Augmented Generation) suffered from context fragmentation whenever queries spanned multi-hop relationships.
        </p>

        <h3 className="text-sm font-bold text-black">1. Knowledge Graph Modeling in Neo4j</h3>
        <p>
          We modeled cross-domain data into an enterprise property graph containing <strong>10,000+ nodes</strong> and <strong>25,000+ relationships</strong>. Node labels were strictly typed, capturing schema relationships between operational telemetry, account structures, and data sources.
        </p>

        <h3 className="text-sm font-bold text-black">2. Cypher LLM Translation Pipeline</h3>
        <p>
          Using LangChain and custom Cypher prompt templates tuned for Azure OpenAI GPT-4, we built a schema-constrained query layer. Before executing any Cypher statement, a validation parser verifies node properties against a strict schema catalog to prevent invalid graph traversals.
        </p>

        <div className="rounded-lg bg-slate-900 p-3 font-mono text-[11px] text-emerald-400">
          <p className="text-slate-400">// Sample Cypher Traversal generated by Graph RAG</p>
          <p>MATCH (a:Account)-[:HAS_TELEMETRY]-&gt;(t:TelemetryData)</p>
          <p>WHERE t.status = &apos;ANOMALY&apos; AND t.timestamp &gt;= datetime().minus(&apos;P7D&apos;)</p>
          <p>RETURN a.name, count(t) AS anomaly_count</p>
        </div>

        <h3 className="text-sm font-bold text-black">3. Results & Business Impact</h3>
        <p>
          By creating an AI semantic layer over the graph, non-technical business intelligence analysts could ask natural language questions. Power BI dashboard scaffolding time dropped by <strong>~60%</strong>.
        </p>
      </div>
    ),
  },
  {
    id: "hft-polymarket",
    title: "Building a High-Frequency Polymarket Trading Engine in C++20 and Reinforcement Learning",
    date: "May 2026",
    readTime: "7 min read",
    tag: "High-Frequency Trading",
    summary:
      "A deep dive into cross-venue arbitrage, price-time matching engines, pybind11 bindings, and PPO reinforcement learning for prediction markets.",
    content: (
      <div className="space-y-4 text-xs leading-relaxed text-black/80">
        <p>
          Prediction markets like Polymarket exhibit short-lived price inefficiencies during macro event announcements. To capture sub-second mispricings, we built a hybrid C++20 and PyTorch trading architecture.
        </p>

        <h3 className="text-sm font-bold text-black">1. Zero-Allocation C++20 Order Engine</h3>
        <p>
          The core matching & order execution engine was implemented in C++20 using cache-aligned lock-free ring buffers and fixed-size memory pools. By avoiding dynamic allocations on the hot path, order submission latency was minimized.
        </p>

        <h3 className="text-sm font-bold text-black">2. PPO Reinforcement Learning & PyTorch</h3>
        <p>
          We trained a Proximal Policy Optimization (PPO) reinforcement learning agent paired with an LSTM actor-critic network on historical order book snapshots. Pybind11 exposes the C++ zero-copy data structures directly to Python for tensor conversion without serialization overhead.
        </p>

        <div className="rounded-lg bg-slate-900 p-3 font-mono text-[11px] text-cyan-300">
          <p className="text-slate-400">// pybind11 low-latency binding snippet</p>
          <p>PYBIND11_MODULE(hft_engine, m) &#123;</p>
          <p>&nbsp;&nbsp;py::class_&lt;OrderBook&gt;(m, &quot;OrderBook&quot;)</p>
          <p>&nbsp;&nbsp;&nbsp;&nbsp;.def(py::init&lt;&gt;())</p>
          <p>&nbsp;&nbsp;&nbsp;&nbsp;.def(&quot;add_limit_order&quot;, &amp;OrderBook::add_limit_order);</p>
          <p>&#125;</p>
        </div>
      </div>
    ),
  },
  {
    id: "colm-benchmark",
    title: "Evaluating Vision-Based LLM Tool Use in Geolocation Reasoning: COLM 2026 Submission",
    date: "March 2026",
    readTime: "4 min read",
    tag: "AI Research",
    summary:
      "Reflections from our research paper submission to COLM 2026 at Algoverse AI on automated location dataset harvesting and multimodal AI benchmarks.",
    content: (
      <div className="space-y-4 text-xs leading-relaxed text-black/80">
        <p>
          While vision LLMs excel at image captioning, complex spatial geolocation reasoning requiring programmatic tool usage remains challenging.
        </p>

        <h3 className="text-sm font-bold text-black">Automated Dataset Generation</h3>
        <p>
          We collected over 300 location datasets using Python, Selenium, and Google Street View APIs with programmatic verification. Our pipeline evaluates whether models can dynamically invoke search, map inspection, and OCR tools to resolve exact coordinates.
        </p>
      </div>
    ),
  },
];

export default function BlogWindow() {
  const [selectedId, setSelectedId] = useState<string | null>(null);

  const selectedArticle = ARTICLES.find((a) => a.id === selectedId);

  return (
    <div className="flex h-full flex-col p-5">
      {selectedArticle ? (
        <div className="space-y-4">
          <button
            type="button"
            onClick={() => {
              sounds.playClick();
              setSelectedId(null);
            }}
            className="inline-flex items-center gap-1 text-xs font-semibold text-blue-600 hover:text-blue-700"
          >
            <ArrowLeft size={14} /> Back to all write-ups
          </button>

          <div>
            <span className="rounded bg-blue-100 px-2 py-0.5 text-[10px] font-bold text-blue-800">
              {selectedArticle.tag}
            </span>
            <h1 className="mt-1.5 text-base font-bold text-black">
              {selectedArticle.title}
            </h1>
            <div className="mt-1 flex items-center gap-3 text-[11px] text-black/50">
              <span className="flex items-center gap-1">
                <Calendar size={12} /> {selectedArticle.date}
              </span>
              <span className="flex items-center gap-1">
                <Clock size={12} /> {selectedArticle.readTime}
              </span>
            </div>
          </div>

          <hr className="border-black/10" />

          {selectedArticle.content}
        </div>
      ) : (
        <div className="space-y-4">
          <div>
            <h1 className="text-base font-bold text-black">Engineering Write-Ups</h1>
            <p className="text-xs text-black/60">
              Technical articles on Graph RAG, C++20 HFT engines, and AI research.
            </p>
          </div>

          <div className="space-y-3">
            {ARTICLES.map((art) => (
              <button
                key={art.id}
                type="button"
                onClick={() => {
                  sounds.playClick();
                  setSelectedId(art.id);
                }}
                className="w-full text-left rounded-xl border border-black/8 bg-white/70 p-4 shadow-sm transition hover:border-blue-400/50 hover:bg-white hover:shadow-md"
              >
                <div className="flex items-center justify-between">
                  <span className="rounded bg-blue-100 px-2 py-0.5 text-[10px] font-bold text-blue-800">
                    {art.tag}
                  </span>
                  <span className="text-[11px] text-black/45">{art.date}</span>
                </div>
                <h2 className="mt-2 text-sm font-bold text-black/90 hover:text-blue-600">
                  {art.title}
                </h2>
                <p className="mt-1 text-xs text-black/65 line-clamp-2">
                  {art.summary}
                </p>
              </button>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
